services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: teamhub
      POSTGRES_USER: teamhub
      POSTGRES_PASSWORD: teamhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
